SMOOTH_PRESET_MIN = 1
SMOOTH_PRESET_MAX = 58

MIDI_CONTROL_CHANGE_FROM_CHRIS 	= 0x20 #Warning : this value is also received from voicelive...
MIDI_CC_CHRIS_NEXT_STEP 		= 127
MIDI_CC_CHRIS_PREVIOUS_STEP 	= 126
MIDI_CC_CHRIS_TALK				= 1
MIDI_CC_CHRIS_NEXT_SLIDE		= 125
MIDI_CC_CHRIS_PREVIOUS_SLIDE	= 124

#Voicelive preset nb
SMOOTH_PRESET_NIGHT_SHADOW_TRAIN 	= 9
SMOOTH_PRESET_L_AVERSE 				= 10
SMOOTH_PRESET_ANOTHER_TOWN			= 11
SMOOTH_PRESET_I_DONT_MIND			= 13
SMOOTH_PRESET_SLAP_MY_HEAD			= 16
SMOOTH_PRESET_LE_BAL 				= 22
SMOOTH_PRESET_AFTER_CHRISTMAS		= 17
SMOOTH_PRESET_RUNNING_ON_THE_WALL	= 18
SMOOTH_PRESET_LES_OMBRES			= 23
SMOOTH_PRESET_DU_SMOOTH				= 24
SMOOTH_PRESET_LE_RENDEZ_VOUS		= 25
SMOOTH_PRESET_BOIPEBA				= 26
SMOOTH_PRESET_CAP_D_HIVER			= 27
SMOOTH_PRESET_IL_Y_AVAIT			= 28
SMOOTH_PRESET_DARKNESS				= 7
SMOOTH_PRESET_KEYWEST				= 8
SMOOTH_PRESET_THE_RIVER				= 12

SName = {}
SName[SMOOTH_PRESET_NIGHT_SHADOW_TRAIN] = "NightShadowTrain"
SName[SMOOTH_PRESET_L_AVERSE] 		= "Laverse"
SName[SMOOTH_PRESET_ANOTHER_TOWN]	= "AnotherTown"
SName[SMOOTH_PRESET_I_DONT_MIND] 	= "IdontMind"
SName[SMOOTH_PRESET_SLAP_MY_HEAD] 	= "SlapMyHead"
SName[SMOOTH_PRESET_LE_BAL] 		= "LeBal"
SName[SMOOTH_PRESET_AFTER_CHRISTMAS] 	= "AfterChristmas"
SName[SMOOTH_PRESET_RUNNING_ON_THE_WALL]= "RunningOnTheWall"
SName[SMOOTH_PRESET_LES_OMBRES] 	= "LesOmbres"
SName[SMOOTH_PRESET_DU_SMOOTH]		= "DuSmooth"
SName[SMOOTH_PRESET_LE_RENDEZ_VOUS] 	= "LeRendezVous"
SName[SMOOTH_PRESET_BOIPEBA] 		= "Boipeba"
SName[SMOOTH_PRESET_CAP_D_HIVER] 	= "CapDhiver"
SName[SMOOTH_PRESET_IL_Y_AVAIT] 	= "IlYavait"
SName[SMOOTH_PRESET_DARKNESS] 		= "Darkness"
SName[SMOOTH_PRESET_KEYWEST]		= "Keywest"
SName[SMOOTH_PRESET_THE_RIVER]		= "TheRiver"

CHRIS_TALK_SLIDE_INDEX						= 20
SToSlide = {}
SToSlide[SMOOTH_PRESET_NIGHT_SHADOW_TRAIN] 	= 2
SToSlide[SMOOTH_PRESET_L_AVERSE] 			= 19
SToSlide[SMOOTH_PRESET_ANOTHER_TOWN]		= 19
SToSlide[SMOOTH_PRESET_I_DONT_MIND] 		= 19
SToSlide[SMOOTH_PRESET_SLAP_MY_HEAD] 		= 26
SToSlide[SMOOTH_PRESET_LE_BAL] 				= 19
SToSlide[SMOOTH_PRESET_AFTER_CHRISTMAS] 	= 19
SToSlide[SMOOTH_PRESET_RUNNING_ON_THE_WALL]	= 19
SToSlide[SMOOTH_PRESET_LES_OMBRES] 			= 19
SToSlide[SMOOTH_PRESET_DU_SMOOTH]			= 19
SToSlide[SMOOTH_PRESET_LE_RENDEZ_VOUS] 		= 19
SToSlide[SMOOTH_PRESET_BOIPEBA] 			= 19
SToSlide[SMOOTH_PRESET_CAP_D_HIVER] 		= 19
SToSlide[SMOOTH_PRESET_IL_Y_AVAIT] 			= 19
SToSlide[SMOOTH_PRESET_DARKNESS] 			= 19
SToSlide[SMOOTH_PRESET_KEYWEST]				= 19
SToSlide[SMOOTH_PRESET_THE_RIVER]			= 19

OBS_COMMAND_SWITCH_SCENE = 1
OBS_SCENE_DEFAULT		= 0
OBS_SCENE_POWERPOINT	= 1

