
#Voicelive preset nb
SMOOTH_PRESET_NIGHT_SHADOW_TRAIN 	= 9
SMOOTH_PRESET_L_AVERSE 			= 10
SMOOTH_PRESET_ANOTHER_TOWN		= 11
SMOOTH_PRESET_I_DONT_MIND		= 13
SMOOTH_PRESET_SLAP_MY_HEAD		= 16
SMOOTH_PRESET_LE_BAL 			= 22
SMOOTH_PRESET_AFTER_CHRISTMAS		= 17
SMOOTH_PRESET_RUNNING_ON_THE_WALL	= 18
SMOOTH_PRESET_LES_OMBRES		= 23
SMOOTH_PRESET_DU_SMOOTH			= 24
SMOOTH_PRESET_LE_RENDEZ_VOUS		= 25
SMOOTH_PRESET_BOIPEBA			= 26
SMOOTH_PRESET_CAP_D_HIVER		= 27
SMOOTH_PRESET_IL_Y_AVAIT		= 28
SMOOTH_PRESET_DARKNESS			= 1
SMOOTH_PRESET_KEYWEST			= 2
SMOOTH_PRESET_THE_RIVER			= 3

SName = {}
SName[SMOOTH_PRESET_NIGHT_SHADOW_TRAIN] = "NightShadowTrain"
SName[SMOOTH_PRESET_L_AVERSE] 		= "Laverse"
SName[SMOOTH_PRESET_ANOTHER_TOWN]	= "AnotherTown"
SName[SMOOTH_PRESET_I_DONT_MIND] 	= "IdontMind"
SName[SMOOTH_PRESET_SLAP_MY_HEAD] 	= "SlapMyHead"
SName[SMOOTH_PRESET_LE_BAL] 		= "LeBal"
SName[SMOOTH_PRESET_AFTER_CHRISTMAS] 	= "AfterChristmas"
SName[SMOOTH_PRESET_RUNNING_ON_THE_WALL]= "RunningOnTheWall"
SName[SMOOTH_PRESET_LES_OMBRES] 	= "LesOmbres"
SName[SMOOTH_PRESET_DU_SMOOTH]		= "DuSmooth"
SName[SMOOTH_PRESET_LE_RENDEZ_VOUS] 	= "LeRendezVous"
SName[SMOOTH_PRESET_BOIPEBA] 		= "Boipeba"
SName[SMOOTH_PRESET_CAP_D_HIVER] 	= "CapDhiver"
SName[SMOOTH_PRESET_IL_Y_AVAIT] 	= "IlYavait"
SName[SMOOTH_PRESET_DARKNESS] 		= "Darkness"
SName[SMOOTH_PRESET_KEYWEST]		= "Keywest"
SName[SMOOTH_PRESET_THE_RIVER]		= "TheRiver"


SMOOTH_PRESET_MIN = 1
SMOOTH_PRESET_MAX = 58
