taskkill /fi "WINDOWTITLE eq VoiceLiveSimu"
taskkill /fi "WINDOWTITLE eq LiveServer"
taskkill /fi "WINDOWTITLE eq VideoManager"
taskkill /fi "WINDOWTITLE eq KeypressManager"
taskkill /fi "WINDOWTITLE eq OSC_QLC_DISPATCH"
taskkill /fi "WINDOWTITLE eq Midi2OSC"
taskkill /fi "WINDOWTITLE eq OBS"
taskkill /fi "WINDOWTITLE eq QLC"
taskkill /fi "WINDOWTITLE eq Cantabile"
taskkill /fi "WINDOWTITLE eq projectM"
taskkill /fi "WINDOWTITLE eq Cantabile Solo (x64)"
taskkill /fi "WINDOWTITLE eq Q Light Controller Plus - ..\QLC_setup.qxw"
taskkill /fi "WINDOWTITLE eq Diaporama PowerPoint - [Smooth trio clips v25.pptx] - PowerPoint"
